### ISSUE TITLE
Subview not aligning with keypath layer

### ISSUE THREAD

**Issue by oblogic7** [airbnb/lottie-ios#1012]
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Expected Behavior 

`addSubview` will result in view being added in correct position relative to the animation keypath.

## Actual Behavior

![image](https://user-images.githubusercontent.com/453840/63561719-8efbc200-c520-11e9-8ebc-17f4b3d34b58.png)
Subview is offset from layer keypath (gray box)

## Code Example

        let textLine1Keypath = AnimationKeypath(keypath: "Line1TextBox")         
        let textLine1Subview = AnimationSubview()
        let textLine1Label = UILabel()
        let replacementText = "UILabel subview text is not aligned"

        textLine1Label.frame = CGRect(x: 0, y: 0, width: 1000, height: 120)
        textLine1Label.adjustsFontSizeToFitWidth = true
        textLine1Label.numberOfLines = 0
        textLine1Label.font = UIFont.init(name: "Avenir", size: 300)
        textLine1Label.text = replacementText.uppercased()
        textLine1Label.textColor = .white
        
        textLine1Subview.addSubview(textLine1Label)

        animationView.addSubview(textLine1Subview, forLayerAt: textLine1Keypath)

## Animation JSON
https://gist.github.com/oblogic7/35f61adeb707b675dc6a9b6716086473

**Comment by carlostrianag** [comment]
@oblogic7 did you manage to solve this?

**Comment by oblogic7** [comment]
Its been a while, but if I remember correctly, I just specified an offset on the frame to line it up.  That may or may not work depending on the use case.

**Comment by carlostrianag** [comment]
@oblogic7 - I'm trying the same offsetting approach. However, I would need a way to calculate the correct position instead of doing some trial and error. Would you be able to share some insights on how to achieve this?

Look at the image below: the red-colored layer should be perfectly aligned with the yellow-colored one. But I'm having a hard time getting this done.

![Simulator Screen Shot - iPhone 11 Pro - 2020-05-14 at 10 33 58](https://user-images.githubusercontent.com/7474390/81954484-84152000-95ce-11ea-85d6-ab1027c0d025.png)


I have added the subview with the following frame structure: X: 0, Y: 0, WIDTH: Same as parent layer, HEIGHT: Same as parent layer ...

and it seems it is getting positioned right in the center of the animation instead of the 0,0 coordinate.

I would appreciate any thought you can share on this, even if it does not work, at least could give me some more ideas to try.

Thanks in advance

**Comment by oblogic7** [comment]
Sorry, I was using a manual offset, so I'm not sure how to calculate those values. Sorry.

**Comment by buba447** [comment]
Should now be fixed by https://github.com/airbnb/lottie-ios/pull/1243

**Comment by thelineh** [comment]
hey I've updated to the latest version and I'm still having this problem, but regarding images just as Carlos
