### ISSUE TITLE
A gradient issue in Lottie 3.1.2

### ISSUE THREAD

**Issue by leegwiro** [airbnb/lottie-ios#1022]
## Check these before submitting:
- [√] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [√] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.1.2

## What Platform are you on? 

- [] MacOS
- [√] iOS

## What Language are you in?
- [√] Swift
- [] Objective-C

## Expected Behavior & Actual Behavior

Please check a video attached. (gradient_impl.zip)
It works fine with version 2.x implemented by objective-C.
However, it does not work with version 3.x implemented by Swift.

[gradient_impl.zip](https://github.com/airbnb/lottie-ios/files/3588811/gradient_impl.zip)

![image](https://user-images.githubusercontent.com/2495384/64506333-35620880-d312-11e9-9e5d-fcb07b926b9f.png)

## Animation JSON

Here is files to help you solve the problem:

[lottie_report.zip](https://github.com/airbnb/lottie-ios/files/3588822/lottie_report.zip)

1. gradient.aep : After Effects project file
2. gradient_render.mp4 : Rendered video in After Effects
3. Gradient.json : json file exported to BodyMovin

**Comment by hhai9x** [comment]
I have same issue.
Using version 2.x will be fine, but still have issue with scaling animation (Fixed at 3.x - https://github.com/airbnb/lottie-ios/pull/932)

Please help!

**Comment by atistank** [comment]
Same problem here with version 3.1.3 :(
Please help us.

**Comment by buba447** [comment]
I've looked into this and it has to do with the layer being scaled. The layer was created at 30x30 px and then scaled up. In lottie 2.5 the scale was applied to the curve before render, in lottie 3+ the scale is applied to the layer rendering the curve which is creating pixelation when scaled up.

This is obviously a regression but I need to think of the best / cleanest way to fix the regression without introducing performance bugs. For now it can be fixed in after effects by manually scaling the path up and resetting the scale of the group/layer to <=100%

**Comment by buba447** [comment]
Added to my todo

**Comment by xquezme** [comment]
@buba447 Any updates on this issue?

**Comment by LexHrabovskyi** [comment]
@buba447 waiting for any updates too

**Comment by calda** [comment]
I believe this is fixed in 3.4.0

**Comment by jhughes696** [comment]
hey @calda , I think this pixelation problem is still happening inn 4.1.2. My coworker @collinleix just posted a similar bug report here:
https://github.com/airbnb/lottie-ios/issues/2066
