### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by vinjegaard** [airbnb/lottie-ios#1081]
## This issue is a:
- [] Crashing Bug

## Which Version of Lottie are you using?
lottie-ios 3.1.5, lottie-react-native 3.3.2

## What Platform are you on? 

- [] MacOS
- [] iOS
- Xcode Version 11.2.1 (11B500)

## What Language are you in?
- [] Swift
- React Native

## Actual Behavior
`Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler` when building. Have removed Pods/ and installed again, tried different toolchains.

Unable to run project does anyone know how to fix this?

Thanks!

**Comment by MrPereir4** [comment]
Im facing the same issue after the update!

**Comment by RanLearns** [comment]
Same here - I can run my project on my laptop in Xcode 11.1, but on my desktop in Xcode 11.2.1 it's "Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler"

**Comment by coreyd303** [comment]
Just recompile your module, either pod update or carthage update should solve this issue. Had the same problem when I upgraded to XCode 11

**Comment by RanLearns** [comment]
just calling carthage update on the existing project did not work for me, but I deleted the framework entirely from the project and then ran carthage update and then re-added the framework to the project and that got things working.

**Comment by vinjegaard** [comment]
@coreyd303 Have tried `pod update` and to remove Pods/ and then `pod install` but I still have this issue.
@RanLearns which files/directories did you delete? But this might not apply for us not using carthage.

**Comment by RanLearns** [comment]
@vinjegaard I deleted the framework itself from Xcode, which deleted the associated files. good luck.

**Comment by MohsanKhan-jayway** [comment]
Xcode 11
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler.

**Comment by Adobels** [comment]
According to [this stackoverflow question](https://stackoverflow.com/q/58654714/1180728) a fix to this issue is to set 
_BUILD_LIBRARY_FOR_DISTRIBUTION = YES;_
in Lottie’s project.pbxproj file.

**Comment by LHJ-K2S** [comment]
I solved this problem by : Go to the directory of the prompt, delete the compiled file and recompile it.

**Comment by Cyberbeni** [comment]
BUILD_LIBRARY_FOR_DISTRIBUTION is used for when you are distributing the framework separately from the app (for example if you have a macOS kernel extension and a framework that communicates with it and someone builds an app that can use this if it's installed on the user's machine), which is not the case here. Just delete derived data and previous build products and you should be good to go.

**Comment by TeplyyMaksim** [comment]
I'm facing the same issue after `react-native run-ios`, but I can run my project via Xcode.

**Comment by wellbranding** [comment]
When this will be enabled? Why can't Lottie add BUILD_LIBRARY_FOR_DISTRIBUTION to its project.pbxproj file?

**Comment by calda** [comment]
Closing since this sounds like a build system issue
