### ISSUE TITLE
Animations with text not displaying anything

### ISSUE THREAD

**Issue by mrferris** [airbnb/lottie-ios#1191]
## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.6 (installed via CocoaPods)

## What Platform are you on? 
- [X] iOS 13.3

## What Language are you in?
- [X] Swift 4.2

## Expected Behavior 
https://lottiefiles.com/share/nVuL52

## Actual Behavior
Any animation that uses text does not show. 
Another example of animation with text not displaying anything is this one: 
https://lottiefiles.com/21921-grrg5grrg-rrtrt

Non-text animation do work perfectly, such as: https://lottiefiles.com/21859-twitter-icon-reaction-cherry-blossom-festival-japan

I saw issue #361, which leads me to believe that text is now supported. 
I expect that my issue is that I'm using something listed as not supported on iOS here: http://airbnb.io/lottie/#/supported-features

Though I'm not sure what I'm using that I should not be using, or how to get what I want to work. 

## Code Example
`animationView = AnimationView(name: "Laila")
animationView.loopMode = .loop
animationView.contentMode = .scaleAspectFit
animationView.setContentCompressionResistancePriority(.fittingSizeLevel, for: .horizontal)
animationView.play()`

## Animation JSON
`{"v":"5.6.9","fr":24,"ip":0,"op":82,"w":1080,"h":1920,"nm":"Comp 1","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"laila 5 Outlines","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[373,997,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0]],"v":[[23,-147],[24,-21],[41,-9]],"c":false},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 4"},{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[77,-73],[111.5,-80],[130.5,-66.75],[130.25,4.5]],"c":false},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 8"},{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[111.75,-50],[89.25,-48.25],[75.5,-39.25],[72.25,-22.25],[84.5,-6.75],[110.75,-18]],"c":false},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 9"},{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[170.5,-79.25],[170.5,-16],[189.5,-7.75],[185.5,-101],[164.5,-113.5]],"c":false},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 6"},{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[225,-190.5],[225,-133.5],[225,-19.5],[243,-8.5]],"c":false},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":-22,"ix":4},"nm":"Mask 7"},{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[280.5,-72],[305,-78],[330.75,-73],[330.25,2.5]],"c":false},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 5"},{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[313.25,-47.25],[296.75,-47.75],[278.5,-43],[272,-31.5],[272.25,-15.25],[283,-5],[300.75,-8.25],[315.5,-18.25]],"c":false},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 10"}],"ef":[{"ty":22,"nm":"Stroke","np":13,"mn":"ADBE Stroke","ix":1,"en":1,"ef":[{"ty":10,"nm":"Path","mn":"ADBE Stroke-0001","ix":1,"v":{"a":0,"k":0,"ix":1}},{"ty":7,"nm":"All Masks","mn":"ADBE Stroke-0010","ix":2,"v":{"a":0,"k":1,"ix":2}},{"ty":7,"nm":"Stroke Sequentially","mn":"ADBE Stroke-0011","ix":3,"v":{"a":0,"k":1,"ix":3}},{"ty":2,"nm":"Color","mn":"ADBE Stroke-0002","ix":4,"v":{"a":0,"k":[1,1,1,1],"ix":4}},{"ty":0,"nm":"Brush Size","mn":"ADBE Stroke-0003","ix":5,"v":{"a":0,"k":20,"ix":5}},{"ty":0,"nm":"Brush Hardness","mn":"ADBE Stroke-0004","ix":6,"v":{"a":0,"k":0.75,"ix":6}},{"ty":0,"nm":"Opacity","mn":"ADBE Stroke-0005","ix":7,"v":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[1]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":61,"s":[1]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":71,"s":[1]},{"t":81,"s":[0]}],"ix":7}},{"ty":0,"nm":"Start","mn":"ADBE Stroke-0008","ix":8,"v":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0]},{"t":61,"s":[0]}],"ix":8}},{"ty":0,"nm":"End","mn":"ADBE Stroke-0009","ix":9,"v":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0]},{"t":61,"s":[100]}],"ix":9}},{"ty":7,"nm":"Spacing","mn":"ADBE Stroke-0006","ix":10,"v":{"a":0,"k":0,"ix":10}},{"ty":7,"nm":"Paint Style","mn":"ADBE Stroke-0007","ix":11,"v":{"a":0,"k":3,"ix":11}}]}],"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[-1.108,-3.099],[-2.021,-2.185],[-2.851,-1.162],[-3.486,0],[-3.515,0.525],[-3.154,0.83],[0,0],[1.438,-0.276],[1.438,0],[1.715,1.855],[0,3.598]],"o":[[0,0],[0,0],[0,3.874],[1.106,3.1],[2.019,2.187],[2.85,1.162],[3.818,0],[3.514,-0.527],[0,0],[-1.44,0.278],[-1.44,0.278],[-2.878,0],[-1.716,-1.853],[0,0]],"v":[[36.44,-125.84],[10.376,-125.84],[10.376,-22.993],[12.036,-12.534],[16.726,-4.607],[24.031,0.415],[33.535,2.158],[44.534,1.37],[54.536,-0.664],[54.536,-19.092],[50.22,-18.262],[45.903,-17.847],[39.014,-20.627],[36.44,-28.804]],"c":true},"ix":2},"nm":"l","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.501959976495,0.329410059312,0.968629964193,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"l","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[24.238,0],[6.336,-1.438],[3.652,-1.881],[0,0],[-10.127,0],[0,-9.297],[0,0],[0,-16.49],[-4.731,-4.676],[-8.246,0],[-5.7,9.519],[0,0],[0,0],[0,0]],"o":[[0,-24.183],[-5.202,0],[-6.337,1.44],[0,0],[9.131,-6.031],[10.071,0],[0,0],[-19.535,2.546],[0,7.803],[4.731,4.677],[11.178,0],[0,0],[0,0],[0,0],[0,0]],"v":[[136.299,-50.801],[99.941,-87.075],[82.634,-84.917],[67.651,-79.937],[67.651,-60.181],[96.538,-69.229],[111.646,-55.283],[88.569,-52.212],[59.268,-23.657],[66.365,-4.939],[85.83,2.075],[111.147,-12.202],[111.479,-12.202],[111.479,0],[136.299,0]],"c":true},"ix":2},"nm":"a","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[3.099,-3.403],[4.925,0],[2.075,1.909],[0,2.988],[-8.523,1.108],[0,0],[0,0]],"o":[[-3.1,3.403],[-3.542,0],[-2.075,-1.909],[0,-6.585],[0,0],[0,0],[0,5.202]],"v":[[106.997,-21.624],[94.961,-16.519],[86.536,-19.382],[83.423,-26.729],[96.206,-38.267],[111.646,-40.259],[111.646,-34.531]],"c":true},"ix":2},"nm":"a","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"mm","mm":1,"nm":"Merge Paths 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"fl","c":{"a":0,"k":[0.501959976495,0.329410059312,0.968629964193,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"a","np":5,"cix":2,"bm":0,"ix":2,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[-2.795,2.546],[0,3.984],[2.794,2.49],[4.482,0],[2.822,-2.49],[0,-3.929],[-2.822,-2.628],[-4.428,0]],"o":[[2.794,-2.545],[0,-3.929],[-2.795,-2.49],[-4.428,0],[-2.822,2.49],[0,3.818],[2.822,2.629],[4.482,0]],"v":[[180.667,-102.266],[184.858,-112.061],[180.667,-121.689],[169.751,-125.425],[158.877,-121.689],[154.644,-112.061],[158.877,-102.39],[169.751,-98.447]],"c":true},"ix":2},"nm":"i","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[-1.108,-3.099],[-2.021,-2.185],[-2.851,-1.162],[-3.486,0],[-3.515,0.525],[-3.154,0.83],[0,0],[1.438,-0.276],[1.438,0],[1.715,1.855],[0,3.598]],"o":[[0,0],[0,0],[0,3.874],[1.106,3.1],[2.019,2.187],[2.85,1.162],[3.818,0],[3.514,-0.527],[0,0],[-1.44,0.278],[-1.44,0.278],[-2.878,0],[-1.716,-1.853],[0,0]],"v":[[182.451,-85],[156.387,-85],[156.387,-22.993],[158.047,-12.534],[162.737,-4.607],[170.042,0.415],[179.546,2.158],[190.544,1.37],[200.547,-0.664],[200.547,-19.092],[196.23,-18.262],[191.914,-17.847],[185.024,-20.627],[182.451,-28.804]],"c":true},"ix":2},"nm":"i","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"mm","mm":1,"nm":"Merge Paths 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"fl","c":{"a":0,"k":[0.501959976495,0.329410059312,0.968629964193,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"i","np":5,"cix":2,"bm":0,"ix":3,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[-1.108,-3.099],[-2.021,-2.185],[-2.851,-1.162],[-3.486,0],[-3.515,0.525],[-3.154,0.83],[0,0],[1.438,-0.276],[1.438,0],[1.715,1.855],[0,3.598]],"o":[[0,0],[0,0],[0,3.874],[1.106,3.1],[2.019,2.187],[2.85,1.162],[3.818,0],[3.514,-0.527],[0,0],[-1.44,0.278],[-1.44,0.278],[-2.878,0],[-1.716,-1.853],[0,0]],"v":[[236.987,-125.84],[210.923,-125.84],[210.923,-22.993],[212.583,-12.534],[217.273,-4.607],[224.578,0.415],[234.082,2.158],[245.081,1.37],[255.083,-0.664],[255.083,-19.092],[250.767,-18.262],[246.45,-17.847],[239.561,-20.627],[236.987,-28.804]],"c":true},"ix":2},"nm":"l","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.501959976495,0.329410059312,0.968629964193,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"l","np":3,"cix":2,"bm":0,"ix":4,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[24.238,0],[6.336,-1.438],[3.652,-1.881],[0,0],[-10.127,0],[0,-9.297],[0,0],[0,-16.49],[-4.731,-4.676],[-8.246,0],[-5.7,9.519],[0,0],[0,0],[0,0]],"o":[[0,-24.183],[-5.202,0],[-6.337,1.44],[0,0],[9.131,-6.031],[10.071,0],[0,0],[-19.535,2.546],[0,7.803],[4.731,4.677],[11.178,0],[0,0],[0,0],[0,0],[0,0]],"v":[[336.846,-50.801],[300.488,-87.075],[283.181,-84.917],[268.198,-79.937],[268.198,-60.181],[297.085,-69.229],[312.192,-55.283],[289.116,-52.212],[259.814,-23.657],[266.912,-4.939],[286.377,2.075],[311.694,-12.202],[312.026,-12.202],[312.026,0],[336.846,0]],"c":true},"ix":2},"nm":"a","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[3.099,-3.403],[4.925,0],[2.075,1.909],[0,2.988],[-8.523,1.108],[0,0],[0,0]],"o":[[-3.1,3.403],[-3.542,0],[-2.075,-1.909],[0,-6.585],[0,0],[0,0],[0,5.202]],"v":[[307.544,-21.624],[295.508,-16.519],[287.083,-19.382],[283.97,-26.729],[296.753,-38.267],[312.192,-40.259],[312.192,-34.531]],"c":true},"ix":2},"nm":"a","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"mm","mm":1,"nm":"Merge Paths 1","mn":"ADBE Vector Filter - Merge","hd":false},{"ty":"fl","c":{"a":0,"k":[0.501959976495,0.329410059312,0.968629964193,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"a","np":5,"cix":2,"bm":0,"ix":5,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":82,"st":0,"bm":0}],"markers":[]}
`

**Comment by giacomocerquone** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-07-13 at 13 38 37](https://user-images.githubusercontent.com/9303791/87300481-335a6e80-c50e-11ea-845c-81291709b927.png)

Actually that example is working fine on react-native and ios-simulator (lottie-ios)

**Comment by giacomocerquone** [comment]
But indeed this one is not working: https://lottiefiles.com/share/nVuL52
In fact, I'm here because I'm experiencing a similar issue with another animation not showing up. I do believe it has to do with some unsupported effects or something else because text works quite fine in animations when they're took from internet.

**Comment by buba447** [comment]
This may have been fixed with https://github.com/airbnb/lottie-ios/pull/1243
Please pull master and verify.

**Comment by yunustek** [comment]
@buba447 
> This may have been fixed with #1243 Please pull master and verify.

I tried on v3.3.0 and problem still happen. My problem is same too :)

My Animation JSON:
`{"v":"5.7.4","fr":29.9700012207031,"ip":0,"op":436.000017758644,"w":750,"h":1624,"nm":"Pre-comp 1","ddd":0,"assets":[],"fonts":{"list":[{"fName":"AnonymousPro-Regular","fFamily":"Anonymous Pro","fStyle":"Regular","ascent":63.6993408203125}]},"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"Shape Layer 6","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[375,812,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":21,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":39,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":60,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":75,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":96,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":114,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":135,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":152,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":173,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":189,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":210,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":224,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":245,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":267,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":288,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":307,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":328,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":346,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":367,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":386,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":408,"s":[{"i":[[5.5,8.5],[0,0],[0,0],[-4.375,-8.25],[0,0],[0,0]],"o":[[-5.5,-8.5],[0,0],[0,0],[4.375,8.25],[0,0],[0,0]],"v":[[-8,160.625],[-27,160.625],[-26.5,181.375],[-7,181.625],[13,181.625],[13,160.625]],"c":true}]},{"t":435.000017717913,"s":[{"i":[[10.238,-9.033],[0,0],[0,0],[-5.133,7.486],[0,0],[0,0]],"o":[[-6.375,5.625],[0,0],[0,0],[6,-8.75],[0,0],[0,0]],"v":[[-8,161],[-27,161],[-26.5,181.75],[-7,182],[13,182],[13,161]],"c":true}]}],"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0,0,0,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":3,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":4496.00018312583,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"Shape Layer 5","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[375,812,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[305,-403.983],[-305,-403.983],[-305,714],[305,714]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0,0,0,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":1,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[99.432,99.576],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":4496.00018312583,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"Shape Layer 4","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[375,812,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[229,-320],[-229,-320],[-229,626],[229,626]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0,0,0,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":1,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":4496.00018312583,"st":0,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"Shape Layer 3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[375,812,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[135,-224],[-133,-224],[-133,530],[135,530]],"c":true},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0,0,0,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":1,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":4496.00018312583,"st":0,"bm":0},{"ddd":0,"ind":5,"ty":4,"nm":"Shape Layer 1","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[371,1004,0],"ix":2,"l":2},"a":{"a":0,"k":[-36,166,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0]],"o":[[0,0],[0,0]],"v":[[-59,135],[-59,190]],"c":false},"ix":2},"nm":"Path 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"st","c":{"a":0,"k":[0,0,0,1],"ix":3},"o":{"a":0,"k":100,"ix":4},"w":{"a":0,"k":3,"ix":5},"lc":1,"lj":1,"ml":4,"bm":0,"nm":"Stroke 1","mn":"ADBE Vector Graphic - Stroke","hd":false},{"ty":"fl","c":{"a":0,"k":[1,1,1,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"bm":0,"nm":"Fill 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"Transform"}],"nm":"Shape 1","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":4496.00018312583,"st":0,"bm":0},{"ddd":0,"ind":6,"ty":5,"nm":"NO NEW DEEPSTORIES 2","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[402,480,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[226.032,-13.796],[-278,-13.592],[-277.903,988.613],[226.13,988.408]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"}],"t":{"d":{"k":[{"s":{"s":32,"f":"AnonymousPro-Regular","t":"NO NEW DEEPSTORIES","j":2,"tr":200,"lh":38.4,"ls":0,"fc":[0,0,0]},"t":0}]},"p":{"m":0,"f":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[1500]},{"t":435.000017717913,"s":[4500]}],"ix":5},"l":{"a":0,"k":0,"ix":6},"a":0,"p":1,"r":1},"m":{"g":1,"a":{"a":0,"k":[0,0],"ix":2}},"a":[]},"ip":0,"op":4496.00018312583,"st":0,"bm":0},{"ddd":0,"ind":7,"ty":5,"nm":"NO NEW DEEPSTORIES","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[402,480,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[226.032,-13.796],[-278,-13.592],[-277.903,988.613],[226.13,988.408]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"}],"t":{"d":{"k":[{"s":{"s":32,"f":"AnonymousPro-Regular","t":"NO NEW DEEPSTORIES","j":2,"tr":200,"lh":38.4,"ls":0,"fc":[0,0,0]},"t":0}]},"p":{"m":0,"f":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[0]},{"t":436.000017758644,"s":[3000]}],"ix":5},"l":{"a":0,"k":0,"ix":6},"a":0,"p":1,"r":1},"m":{"g":1,"a":{"a":0,"k":[0,0],"ix":2}},"a":[]},"ip":0,"op":4496.00018312583,"st":0,"bm":0},{"ddd":0,"ind":8,"ty":5,"nm":"NO NEW DEEPSTORIES 4","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[402,572,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[132.032,-14],[-196,-13.796],[-195.968,808.408],[132.065,808.204]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"}],"t":{"d":{"k":[{"s":{"s":32,"f":"AnonymousPro-Regular","t":"NO NEW DEEPSTORIES","j":2,"tr":200,"lh":38.4,"ls":0,"fc":[0,0,0]},"t":0}]},"p":{"m":0,"f":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[800]},{"t":436.000017758644,"s":[3105]}],"ix":5},"l":{"a":0,"k":0,"ix":6},"a":0,"p":1,"r":1},"m":{"g":1,"a":{"a":0,"k":[0,0],"ix":2}},"a":[]},"ip":0,"op":4496.00018312583,"st":0,"bm":0},{"ddd":0,"ind":9,"ty":5,"nm":"NO NEW DEEPSTORIES 3","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[402,572,0],"ix":2,"l":2},"a":{"a":0,"k":[0,0,0],"ix":1,"l":2},"s":{"a":0,"k":[100,100,100],"ix":6,"l":2}},"ao":0,"hasMask":true,"masksProperties":[{"inv":false,"mode":"n","pt":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0]],"v":[[132.032,-14],[-196,-13.796],[-195.968,808.408],[132.065,808.204]],"c":true},"ix":1},"o":{"a":0,"k":100,"ix":3},"x":{"a":0,"k":0,"ix":4},"nm":"Mask 1"}],"t":{"d":{"k":[{"s":{"s":32,"f":"AnonymousPro-Regular","t":"NO NEW DEEPSTORIES","j":2,"tr":200,"lh":38.4,"ls":0,"fc":[0,0,0]},"t":0}]},"p":{"m":0,"f":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0,"s":[1940]},{"t":436.000017758644,"s":[4240]}],"ix":5},"l":{"a":0,"k":0,"ix":6},"a":0,"p":1,"r":1},"m":{"g":1,"a":{"a":0,"k":[0,0],"ix":2}},"a":[]},"ip":0,"op":4496.00018312583,"st":0,"bm":0}],"markers":[],"chars":[{"ch":"N","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[43.115,-63.721],[36.328,-63.721],[36.328,-12.305],[11.803,-63.721],[2.393,-63.721],[2.393,0],[9.082,0],[9.082,-53.906],[34.814,0],[43.115,0]],"c":true},"ix":2},"nm":"N","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"N","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":"O","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0.911,3.972],[1.92,3.06],[3.108,1.839],[4.395,0],[3.108,-1.839],[1.969,-3.059],[0.862,-3.971],[0,-4.264],[-0.862,-3.971],[-1.937,-3.027],[-3.109,-1.839],[-4.46,0],[-3.109,1.839],[-1.921,3.027],[-0.879,3.972],[0,4.265]],"o":[[-0.912,-3.971],[-1.921,-3.059],[-3.109,-1.839],[-4.395,0],[-3.109,1.839],[-1.97,3.06],[-0.862,3.972],[0,4.265],[0.862,3.972],[1.936,3.027],[3.108,1.839],[4.459,0],[3.108,-1.839],[1.92,-3.027],[0.879,-3.971],[0,-4.264]],"v":[[45.85,-44.141],[41.602,-54.688],[34.058,-62.036],[22.803,-64.795],[11.548,-62.036],[3.931,-54.688],[-0.317,-44.141],[-1.611,-31.787],[-0.317,-19.434],[3.882,-8.936],[11.45,-1.636],[22.803,1.123],[34.155,-1.636],[41.699,-8.936],[45.898,-19.434],[47.217,-31.787]],"c":true},"ix":2},"nm":"O","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[0.52,-3.239],[1.366,-2.588],[2.275,-1.643],[3.445,0],[2.259,1.644],[1.366,2.588],[0.536,3.239],[0,3.191],[-0.536,3.223],[-1.366,2.637],[-2.259,1.628],[-3.479,0],[-2.194,-1.253],[-1.495,-2.376],[-0.797,-3.369],[0,-4.199]],"o":[[-0.52,3.239],[-1.366,2.588],[-2.275,1.644],[-3.479,0],[-2.259,-1.643],[-1.366,-2.588],[-0.536,-3.239],[0,-3.223],[0.536,-3.223],[1.366,-2.637],[2.259,-1.627],[2.795,0],[2.194,1.254],[1.495,2.377],[0.797,3.369],[0,3.191]],"v":[[39.649,-22.144],[36.821,-13.403],[31.36,-7.056],[22.778,-4.59],[14.172,-7.056],[8.735,-13.403],[5.882,-22.144],[5.078,-31.787],[5.882,-41.455],[8.735,-50.244],[14.172,-56.641],[22.778,-59.082],[30.263,-57.202],[35.797,-51.758],[39.235,-43.14],[40.43,-31.787]],"c":true},"ix":2},"nm":"O","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"O","np":5,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":" ","size":32,"style":"Regular","w":54.59,"data":{},"fFamily":"Anonymous Pro"},{"ch":"E","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[43.115,-5.713],[9.082,-5.713],[9.082,-29.492],[34.18,-29.492],[34.18,-35.205],[9.082,-35.205],[9.082,-58.008],[43.115,-58.008],[43.115,-63.721],[2.393,-63.721],[2.393,0],[43.115,0]],"c":true},"ix":2},"nm":"E","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"E","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":"W","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[41.406,-63.721],[32.422,-11.279],[25.977,-45.508],[19.385,-45.508],[12.988,-11.279],[4.004,-63.721],[-3.076,-63.721],[8.301,0],[16.113,0],[22.705,-31.104],[29.199,0],[37.109,0],[48.584,-63.721]],"c":true},"ix":2},"nm":"W","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"W","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":"D","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0.928,3.841],[1.969,2.93],[3.108,1.742],[4.329,0],[0,0],[0,0],[0,0],[-3.109,1.693],[-1.97,2.914],[-0.896,3.857],[0,4.265]],"o":[[-0.928,-3.841],[-1.97,-2.93],[-3.109,-1.741],[0,0],[0,0],[0,0],[4.395,0],[3.108,-1.692],[1.969,-2.913],[0.895,-3.857],[0,-4.264]],"v":[[46.216,-43.945],[41.87,-54.102],[34.253,-61.108],[23.096,-63.721],[2.393,-63.721],[2.393,0],[23.096,0],[34.351,-2.539],[41.968,-9.448],[46.265,-19.604],[47.607,-31.787]],"c":true},"ix":2},"nm":"D","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[3.141,-4.524],[5.598,0],[0,0],[0,0],[0,0],[-3.142,-4.573],[0,-8.333]],"o":[[-3.142,4.525],[0,0],[0,0],[0,0],[5.598,0],[3.141,4.574],[0,8.334]],"v":[[36.206,-12.5],[23.096,-5.713],[9.082,-5.713],[9.082,-58.008],[23.096,-58.008],[36.206,-51.147],[40.918,-31.787]],"c":true},"ix":2},"nm":"D","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"D","np":5,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":"P","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[3.841,3.044],[6.998,0],[0,0],[0,0],[0,0],[0,0],[0,0],[-3.841,2.995],[0,6.152]],"o":[[-3.841,-3.043],[0,0],[0,0],[0,0],[0,0],[0,0],[6.934,0],[3.841,-2.995],[0,-6.055]],"v":[[39.648,-59.155],[23.389,-63.721],[2.393,-63.721],[2.393,0],[9.082,0],[9.082,-27.295],[23.486,-27.295],[39.648,-31.787],[45.41,-45.508]],"c":true},"ix":2},"nm":"P","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[2.766,-1.969],[4.622,0],[0,0],[0,0],[0,0],[-2.767,-1.969],[0,-4.395]],"o":[[-2.767,1.97],[0,0],[0,0],[0,0],[4.622,0],[2.766,1.97],[0,4.395]],"v":[[34.57,-35.962],[23.486,-33.008],[9.082,-33.008],[9.082,-58.008],[23.486,-58.008],[34.57,-55.054],[38.721,-45.508]],"c":true},"ix":2},"nm":"P","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"P","np":5,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":"S","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[1.204,2.132],[1.888,1.465],[2.376,1.042],[2.409,0.847],[1.839,0.732],[1.399,0.896],[0.83,1.172],[0,1.66],[-0.7,1.367],[-1.172,0.863],[-1.562,0.391],[-1.726,0],[-1.758,-0.7],[-1.367,-1.188],[-0.798,-1.676],[0,-1.92],[0,0],[0,0],[0,0],[0,0],[2.62,1.27],[3.092,0],[2.376,-0.732],[1.79,-1.399],[1.106,-2.034],[0,-2.604],[-1.14,-1.969],[-1.823,-1.367],[-2.312,-0.895],[-2.312,-0.813],[-1.888,-0.732],[-1.514,-1.041],[-0.896,-1.465],[0,-2.051],[0.7,-1.432],[1.204,-0.993],[1.595,-0.537],[1.888,0],[2.034,0.732],[1.562,1.302],[1.009,1.807],[0,2.181],[0,0],[0,0],[0,0],[0,0],[-2.995,-1.334],[-3.581,0],[-2.409,0.846],[-1.855,1.562],[-1.107,2.165],[0,2.67]],"o":[[-1.205,-2.132],[-1.888,-1.465],[-2.377,-1.041],[-1.921,-0.748],[-1.839,-0.732],[-1.4,-0.895],[-0.83,-1.172],[0,-1.888],[0.7,-1.367],[1.172,-0.862],[1.562,-0.391],[1.953,0],[1.758,0.7],[1.367,1.189],[0.797,1.677],[0,0],[0,0],[0,0],[0,0],[-1.465,-2.604],[-2.621,-1.27],[-2.507,0],[-2.377,0.732],[-1.791,1.4],[-1.107,2.035],[0,2.93],[1.139,1.97],[1.823,1.367],[2.311,0.896],[1.953,0.716],[1.888,0.732],[1.514,1.042],[0.895,1.465],[0,1.823],[-0.7,1.433],[-1.205,0.993],[-1.595,0.537],[-2.116,0],[-2.035,-0.732],[-1.562,-1.302],[-1.009,-1.807],[0,0],[0,0],[0,0],[0,0],[1.758,2.605],[2.995,1.334],[2.604,0],[2.409,-0.846],[1.855,-1.562],[1.106,-2.164],[0,-3.059]],"v":[[42.09,-24.39],[37.451,-29.785],[31.055,-33.545],[23.877,-36.377],[18.237,-38.599],[13.379,-41.04],[10.034,-44.141],[8.789,-48.389],[9.839,-53.271],[12.646,-56.616],[16.748,-58.496],[21.68,-59.082],[27.246,-58.032],[31.934,-55.2],[35.181,-50.903],[36.377,-45.508],[42.285,-45.508],[42.285,-63.721],[36.377,-63.721],[36.377,-57.08],[30.249,-62.891],[21.68,-64.795],[14.355,-63.696],[8.105,-60.498],[3.76,-55.347],[2.1,-48.389],[3.809,-41.04],[8.252,-36.035],[14.453,-32.642],[21.387,-30.078],[27.148,-27.905],[32.251,-25.244],[35.864,-21.484],[37.207,-16.211],[36.157,-11.328],[33.301,-7.69],[29.102,-5.396],[23.877,-4.59],[17.651,-5.688],[12.256,-8.74],[8.398,-13.403],[6.885,-19.385],[1.221,-19.385],[1.221,0],[6.885,0],[6.885,-6.787],[14.014,-0.879],[23.877,1.123],[31.396,-0.146],[37.793,-3.76],[42.236,-9.351],[43.896,-16.602]],"c":true},"ix":2},"nm":"S","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"S","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":"T","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[45.508,-63.721],[0,-63.721],[0,-42.188],[5.713,-42.188],[5.713,-58.008],[19.385,-58.008],[19.385,-5.713],[9.082,-5.713],[9.082,0],[36.426,0],[36.426,-5.713],[26.172,-5.713],[26.172,-58.008],[39.795,-58.008],[39.795,-42.188],[45.508,-42.188]],"c":true},"ix":2},"nm":"T","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"T","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":"R","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[-2.263,0.912],[-1.628,1.498],[-0.945,2.132],[0,2.67],[3.841,3.044],[6.998,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[2.669,-0.195],[2.262,-0.911],[1.627,-1.497],[0.944,-2.132],[0,-6.055],[-3.841,-3.043],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[26.904,-27.588],[34.302,-29.248],[40.137,-32.861],[43.994,-38.306],[45.41,-45.508],[39.648,-59.155],[23.389,-63.721],[2.393,-63.721],[2.393,0],[9.082,0],[9.082,-27.295],[18.994,-27.295],[37.598,0],[46.094,0]],"c":true},"ix":2},"nm":"R","mn":"ADBE Vector Shape - Group","hd":false},{"ind":1,"ty":"sh","ix":2,"ks":{"a":0,"k":{"i":[[2.686,-1.969],[4.688,0],[0,0],[0,0],[0,0],[-2.686,-2.002],[0,-4.329]],"o":[[-2.686,1.97],[0,0],[0,0],[0,0],[4.688,0],[2.686,2.002],[0,4.395]],"v":[[34.448,-35.962],[23.389,-33.008],[9.082,-33.008],[9.082,-58.008],[23.389,-58.008],[34.448,-55.005],[38.477,-45.508]],"c":true},"ix":2},"nm":"R","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"R","np":5,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"},{"ch":"I","size":32,"style":"Regular","w":54.59,"data":{"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"o":[[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,0]],"v":[[36.426,-5.713],[26.172,-5.713],[26.172,-58.008],[36.426,-58.008],[36.426,-63.721],[9.082,-63.721],[9.082,-58.008],[19.385,-58.008],[19.385,-5.713],[9.082,-5.713],[9.082,0],[36.426,0]],"c":true},"ix":2},"nm":"I","mn":"ADBE Vector Shape - Group","hd":false}],"nm":"I","np":3,"cix":2,"bm":0,"ix":1,"mn":"ADBE Vector Group","hd":false}]},"fFamily":"Anonymous Pro"}]}`

**Comment by roimulia2** [comment]
Did you fix it by chance?

**Comment by calda** [comment]
Text layers are now supported
