### ISSUE TITLE
Bad/poor quality animation on iOS Player (Web Player is fine)

### ISSUE THREAD

**Issue by edreyyo** [airbnb/lottie-ios#1467]
## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
Lottie 3.2.3

## What Platform are you on? 
- [X] iOS

## Expected Behavior 
<img width="368" alt="web" src="https://user-images.githubusercontent.com/6125211/148510236-aeb2a690-4b15-4596-bb16-13636982c342.png">

## Actual Behavior
<img width="374" alt="ios" src="https://user-images.githubusercontent.com/6125211/148510246-bd35d550-9465-4149-a262-4a7f0f6dc152.png">

## Animation JSON
JSON filed emailed to brandon@withrow.io

## Additional info
The animation quality is really low on iOS but web is fine. Is this a bug?

**Comment by calda** [comment]
This may have been a regression in 3.2.3 that was fixed in 3.3.0 (https://github.com/airbnb/lottie-ios/pull/1436). Could you update to 3.3.0 and see if it works properly on that version?

**Comment by edreyyo** [comment]
@calda Thanks for the reply. I used the `Example` project from this repo, loaded my animation and the problem still persists. Is there anything I can do from my side to help debug the issue?

**Comment by calda** [comment]
Could you share a copy of your animation? (If it's private, could you email to to cal.stephens@airbnb.com?)

**Comment by edreyyo** [comment]
@calda I have just emailed you the animation file. Sorry for the delay.

**Comment by calda** [comment]
Thanks for sending the animation file. I see the issue you're talking about when I run your animation locally.

Some good news: I'm working on an experimental [new rendering engine](https://github.com/airbnb/lottie-ios/blob/master/Sources/Private/Experimental/ExperimentalFeatureConfiguration.swift#L21) that uses Core Animation. The new rendering engine doesn't have this problem!

| Existing production engine | New experimental engine |
| ----- | ----- |
| <img width="177" alt="Screen Shot 2022-01-19 at 2 22 07 PM" src="https://user-images.githubusercontent.com/1811727/150225808-007644ad-bb36-46a5-b018-8ad8a70ea371.png"> | <img width="184" alt="Screen Shot 2022-01-19 at 2 22 23 PM" src="https://user-images.githubusercontent.com/1811727/150225850-f8026a4d-a5f8-436a-91b9-0690b48762a2.png"> |

I am currently working on productionizing the new engine. It's still missing some features present in the existing engine, but appears to support the features used by your animation. It isn't "officially" available, but if you want to unblock yourself asap you could experiment with using the new engine. There's a [feature flag](https://github.com/airbnb/lottie-ios/blob/master/Sources/Private/Experimental/ExperimentalFeatureConfiguration.swift#L21) that you could use to enable the experimental engine (either globally, or for this specific `AnimationView`).

**Comment by edreyyo** [comment]
Thanks for the good news, @calda. Awesome to hear your new engine solves the problem.

I have temporarily downgraded to a previous version of Lottie but will definitely upgrade once your improvements are officially available.

Thanks for all the hard work you have put into this!

**Comment by calda** [comment]
Closing since the Core Animation rendering engine is now available in 3.4.0

**Comment by kahlan88** [comment]
Hi, one of our projects is having a similar issue on an Android.
Does the new engine, resolve this issue too: https://github.com/lottie-react-native/lottie-react-native/issues/809

As I haven't got access to the codebase on that project, I am unable to determine the version of lottie it's using, but I'm trying to find that out in the meantime.

Is the new engine working fine on Android too?

**Comment by calda** [comment]
The new rendering engine is only available on iOS, not Android. I'd suggest opening an issue on http://github.com/airbnb/lottie-android.
