### ISSUE TITLE
Crashes on WebThread and main thread

### ISSUE THREAD

**Issue by banshchikov** [airbnb/lottie-ios#507]
## 
Hi guys! Few weeks ago I added Lottie to our projects. There are some strange crashes. At the moment I don't know how to reproduce them.

## Check these before submitting:
- [x] Updated to the latest (2.1.3) version of Lottie
- [x] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ ] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [x] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [x] iOS (Specify Platform Version)

## Animation JSON
We have plenty animations. I don't know which can cause problem. I added one of them.
[icon_1.json.zip](https://github.com/airbnb/lottie-ios/files/1514458/icon_1.json.zip)

## Crashes

**iPhone 5c, iOS 10.3.2**

```
Crashed: WebThread
0  libobjc.A.dylib                0x1b078dc6 objc_msgSend + 5
1  REDFonbet                      0x779279 __70-[LOTTrimPathNode updateWithFrame:withModifierBlock:forceLocalUpdate:]_block_invoke (LOTTrimPathNode.m:66)
2  REDFonbet                      0x763239 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:60)
3  REDFonbet                      0x763205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
4  REDFonbet                      0x77915d -[LOTTrimPathNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTTrimPathNode.m:62)
5  REDFonbet                      0x771e07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
6  REDFonbet                      0x771e07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
7  REDFonbet                      0x76d4d7 -[LOTLayerContainer displayWithFrame:forceUpdate:] (LOTLayerContainer.m:239)
8  REDFonbet                      0x767381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
9  REDFonbet                      0x767381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
10 REDFonbet                      0x76d231 -[LOTLayerContainer display] (LOTLayerContainer.m:214)
11 QuartzCore                     0x1ec5eb9f CA::Layer::display_if_needed(CA::Transaction*) + 208
12 QuartzCore                     0x1ec5ec0d CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
13 QuartzCore                     0x1ebed839 CA::Context::commit_transaction(CA::Transaction*) + 320
14 QuartzCore                     0x1ec0bfdb CA::Transaction::commit() + 578
15 QuartzCore                     0x1ec0cb2f CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 162
16 CoreFoundation                 0x1bd9f803 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
17 CoreFoundation                 0x1bd9da55 __CFRunLoopDoObservers + 282
18 CoreFoundation                 0x1bcf11cf CFRunLoopRunSpecific + 502
19 CoreFoundation                 0x1bcf0fd1 CFRunLoopRunInMode + 104
20 WebCore                        0x1ff12de3 RunWebThread(void*) + 426
21 libsystem_pthread.dylib        0x1b66893b _pthread_body + 216
22 libsystem_pthread.dylib        0x1b66885d _pthread_start + 234
23 libsystem_pthread.dylib        0x1b666468 thread_start + 8
```

```
Crashed: com.apple.main-thread
0  CoreFoundation                 0x1bda18c8 _CFRelease + 1369
1  REDFonbet                      0x7edbfb -[LOTBezierPath dealloc] (LOTBezierPath.m:68)
2  REDFonbet                      0x7edbfb -[LOTBezierPath dealloc] (LOTBezierPath.m:68)
3  libobjc.A.dylib                0x1b085259 objc_object::sidetable_release(bool) + 238
4  REDFonbet                      0x7fb04f -[LOTRenderGroup performLocalUpdate] (LOTRenderGroup.m:150)
5  REDFonbet                      0x7ec229 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:55)
6  REDFonbet                      0x7fae3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
7  REDFonbet                      0x7ec205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
8  REDFonbet                      0x7fae3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
9  REDFonbet                      0x7ec205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
10 REDFonbet                      0x7fae3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
11 REDFonbet                      0x7fae07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
12 REDFonbet                      0x7f64d7 -[LOTLayerContainer displayWithFrame:forceUpdate:] (LOTLayerContainer.m:239)
13 REDFonbet                      0x7f0381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
14 REDFonbet                      0x7f0381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
15 REDFonbet                      0x7f6231 -[LOTLayerContainer display] (LOTLayerContainer.m:214)
16 QuartzCore                     0x1ec5eb9f CA::Layer::display_if_needed(CA::Transaction*) + 208
17 QuartzCore                     0x1ec5ec0d CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
18 QuartzCore                     0x1ebed839 CA::Context::commit_transaction(CA::Transaction*) + 320
19 QuartzCore                     0x1ec0bfdb CA::Transaction::commit() + 578
20 QuartzCore                     0x1ec0cb2f CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 162
21 CoreFoundation                 0x1bd9f803 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
22 CoreFoundation                 0x1bd9da55 __CFRunLoopDoObservers + 282
23 CoreFoundation                 0x1bd9e017 __CFRunLoopRun + 1358
24 CoreFoundation                 0x1bcf11af CFRunLoopRunSpecific + 470
25 CoreFoundation                 0x1bcf0fd1 CFRunLoopRunInMode + 104
26 GraphicsServices               0x1d49bb41 GSEventRunModal + 80
27 UIKit                          0x21072e13 UIApplicationMain + 150
28 REDFonbet                      0x598ecd main (main.m:14)
29 libdyld.dylib                  0x1b4de4eb start + 2
```

```
Crashed: WebThread
0  libobjc.A.dylib                0x1b0846e4 objc_release + 3
1  REDFonbet                      0x80fbfb -[LOTBezierPath dealloc] (LOTBezierPath.m:68)
2  libobjc.A.dylib                0x1b085259 objc_object::sidetable_release(bool) + 238
3  REDFonbet                      0x80e4cb -[LOTAnimatorNode rebuildOutputs] (LOTAnimatorNode.m:92)
4  REDFonbet                      0x80e25b -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:45)
5  REDFonbet                      0x80e205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
6  REDFonbet                      0x81ce07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
7  REDFonbet                      0x81ce07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
8  REDFonbet                      0x80e205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
9  REDFonbet                      0x81ce3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
10 REDFonbet                      0x80e205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
11 REDFonbet                      0x81ce3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
12 REDFonbet                      0x80e205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
13 REDFonbet                      0x81ce3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
14 REDFonbet                      0x80e205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
15 REDFonbet                      0x81ce3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
16 REDFonbet                      0x80e205 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
17 REDFonbet                      0x81ce3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
18 REDFonbet                      0x81ce07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
19 REDFonbet                      0x8184d7 -[LOTLayerContainer displayWithFrame:forceUpdate:] (LOTLayerContainer.m:239)
20 REDFonbet                      0x812381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
21 REDFonbet                      0x812381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
22 REDFonbet                      0x818231 -[LOTLayerContainer display] (LOTLayerContainer.m:214)
23 QuartzCore                     0x1ec5eb9f CA::Layer::display_if_needed(CA::Transaction*) + 208
24 QuartzCore                     0x1ec5ec0d CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
25 QuartzCore                     0x1ebed839 CA::Context::commit_transaction(CA::Transaction*) + 320
26 QuartzCore                     0x1ec0bfdb CA::Transaction::commit() + 578
27 QuartzCore                     0x1ec0cb2f CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 162
28 CoreFoundation                 0x1bd9f803 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
29 CoreFoundation                 0x1bd9da55 __CFRunLoopDoObservers + 282
30 CoreFoundation                 0x1bcf11cf CFRunLoopRunSpecific + 502
31 CoreFoundation                 0x1bcf0fd1 CFRunLoopRunInMode + 104
32 WebCore                        0x1ff12de3 RunWebThread(void*) + 426
33 libsystem_pthread.dylib        0x1b66893b _pthread_body + 216
34 libsystem_pthread.dylib        0x1b66885d _pthread_start + 234
35 libsystem_pthread.dylib        0x1b666468 thread_start + 8
```

```
Crashed: WebThread
0  libobjc.A.dylib                0x1b0846e4 objc_release + 3
1  REDFonbet                      0x75bbfb -[LOTBezierPath dealloc] (LOTBezierPath.m:68)
2  libobjc.A.dylib                0x1b085259 objc_object::sidetable_release(bool) + 238
3  REDFonbet                      0x75a25b -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:45)
4  REDFonbet                      0x768e3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
5  REDFonbet                      0x768e07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
6  REDFonbet                      0x7644d7 -[LOTLayerContainer displayWithFrame:forceUpdate:] (LOTLayerContainer.m:239)
7  REDFonbet                      0x75e381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
8  REDFonbet                      0x75e381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
9  REDFonbet                      0x764231 -[LOTLayerContainer display] (LOTLayerContainer.m:214)
10 QuartzCore                     0x1ec5eb9f CA::Layer::display_if_needed(CA::Transaction*) + 208
11 QuartzCore                     0x1ec5ec0d CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
12 QuartzCore                     0x1ebed839 CA::Context::commit_transaction(CA::Transaction*) + 320
13 QuartzCore                     0x1ec0bfdb CA::Transaction::commit() + 578
14 QuartzCore                     0x1ec0cb2f CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 162
15 CoreFoundation                 0x1bd9f803 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
16 CoreFoundation                 0x1bd9da55 __CFRunLoopDoObservers + 282
17 CoreFoundation                 0x1bcf11cf CFRunLoopRunSpecific + 502
18 CoreFoundation                 0x1bcf0fd1 CFRunLoopRunInMode + 104
19 WebCore                        0x1ff12de3 RunWebThread(void*) + 426
20 libsystem_pthread.dylib        0x1b66893b _pthread_body + 216
21 libsystem_pthread.dylib        0x1b66885d _pthread_start + 234
22 libsystem_pthread.dylib        0x1b666468 thread_start + 8
```

```
Crashed: WebThread
0  libobjc.A.dylib                0x1b0846e4 objc_release + 3
1  REDFonbet                      0x75bbfb -[LOTBezierPath dealloc] (LOTBezierPath.m:68)
2  libobjc.A.dylib                0x1b085259 objc_object::sidetable_release(bool) + 238
3  REDFonbet                      0x75a25b -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:45)
4  REDFonbet                      0x768e3b -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
5  REDFonbet                      0x768e07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
6  REDFonbet                      0x7644d7 -[LOTLayerContainer displayWithFrame:forceUpdate:] (LOTLayerContainer.m:239)
7  REDFonbet                      0x75e381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
8  REDFonbet                      0x75e381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
9  REDFonbet                      0x764231 -[LOTLayerContainer display] (LOTLayerContainer.m:214)
10 QuartzCore                     0x1ec5eb9f CA::Layer::display_if_needed(CA::Transaction*) + 208
11 QuartzCore                     0x1ec5ec0d CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
12 QuartzCore                     0x1ebed839 CA::Context::commit_transaction(CA::Transaction*) + 320
13 QuartzCore                     0x1ec0bfdb CA::Transaction::commit() + 578
14 QuartzCore                     0x1ec0cb2f CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 162
15 CoreFoundation                 0x1bd9f803 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
16 CoreFoundation                 0x1bd9da55 __CFRunLoopDoObservers + 282
17 CoreFoundation                 0x1bcf11cf CFRunLoopRunSpecific + 502
18 CoreFoundation                 0x1bcf0fd1 CFRunLoopRunInMode + 104
19 WebCore                        0x1ff12de3 RunWebThread(void*) + 426
20 libsystem_pthread.dylib        0x1b66893b _pthread_body + 216
21 libsystem_pthread.dylib        0x1b66885d _pthread_start + 234
22 libsystem_pthread.dylib        0x1b666468 thread_start + 8
```

```
Crashed: com.apple.main-thread
0  CoreGraphics                   0x1d0b4c0c CG::Path::Sequence::operator==(CG::Path::Shape const&) const + 11
1  CoreGraphics                   0x1d167d0d CG::Path::operator==(CG::Path const&) const + 16
2  CoreGraphics                   0x1d167d0d CG::Path::operator==(CG::Path const&) const + 16
3  CoreGraphics                   0x1d1f664b CGPathEqualToPath + 106
4  CoreGraphics                   0x1d1f83ab path_equal(void const*, void const*) + 28
5  CoreFoundation                 0x1bcee729 CFEqual + 204
6  QuartzCore                     0x1eb984f3 CAValueEqual + 118
7  QuartzCore                     0x1ec60409 CA::Layer::setter(unsigned int, _CAValueType, void const*) + 160
8  QuartzCore                     0x1ec5b239 CALayer_setter_kCAValueRetainedPointer + 32
9  QuartzCore                     0x1ec9d8bb -[CAShapeLayer setPath:] + 38
10 REDFonbet                      0x80cf13 -[LOTStrokeRenderer rebuildOutputs] (LOTStrokeRenderer.m:113)
11 REDFonbet                      0x7f825b -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:45)
12 REDFonbet                      0x80e15d -[LOTTrimPathNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTTrimPathNode.m:62)
13 REDFonbet                      0x806e07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
14 REDFonbet                      0x806e07 -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
15 REDFonbet                      0x8024d7 -[LOTLayerContainer displayWithFrame:forceUpdate:] (LOTLayerContainer.m:239)
16 REDFonbet                      0x7fc381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
17 REDFonbet                      0x7fc381 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
18 REDFonbet                      0x802231 -[LOTLayerContainer display] (LOTLayerContainer.m:214)
19 QuartzCore                     0x1ec5eb9f CA::Layer::display_if_needed(CA::Transaction*) + 208
20 QuartzCore                     0x1ec5ec0d CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
21 QuartzCore                     0x1ebed839 CA::Context::commit_transaction(CA::Transaction*) + 320
22 QuartzCore                     0x1ec0bfdb CA::Transaction::commit() + 578
23 QuartzCore                     0x1ec0cb2f CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 162
24 CoreFoundation                 0x1bd9f803 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
25 CoreFoundation                 0x1bd9da55 __CFRunLoopDoObservers + 282
26 CoreFoundation                 0x1bd9e017 __CFRunLoopRun + 1358
27 CoreFoundation                 0x1bcf11af CFRunLoopRunSpecific + 470
28 CoreFoundation                 0x1bcf0fd1 CFRunLoopRunInMode + 104
29 GraphicsServices               0x1d49bb41 GSEventRunModal + 80
30 UIKit                          0x21072e13 UIApplicationMain + 150
31 REDFonbet                      0x5a4ecd main (main.m:14)
32 libdyld.dylib                  0x1b4de4eb start + 2
```

**iPhone 7 Plus, iOS 11.1.0**

```
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x184ab5348 __pthread_kill + 8
1  libsystem_pthread.dylib        0x184bc9344 pthread_kill$VARIANT$mp + 396
2  libsystem_c.dylib              0x184a24fb8 abort + 140
3  libsystem_malloc.dylib         0x184aecd18 szone_size + 634
4  CoreGraphics                   0x186822d54 std::__1::__vector_base<CG::Path::Subpath, CG::Allocator<CG::Path::Subpath> >::~__vector_base() + 72
5  CoreGraphics                   0x186822ca0 CG::Path::Sequence::~Sequence() + 36
6  CoreGraphics                   0x1868f521c CG::Path::~Path() + 60
7  CoreFoundation                 0x184f47ad4 _CFRelease + 224
8  REDFonbet                      0x10377485c -[LOTBezierPath dealloc] (LOTBezierPath.m:68)
9  REDFonbet                      0x103783314 -[LOTRenderGroup rebuildOutputs] (LOTRenderGroup.m:159)
10 REDFonbet                      0x103772a48 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:61)
11 REDFonbet                      0x10378300c -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
12 REDFonbet                      0x1037729f4 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
13 REDFonbet                      0x10378300c -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
14 REDFonbet                      0x1037729f4 -[LOTAnimatorNode updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTAnimatorNode.m:49)
15 REDFonbet                      0x10378300c -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:137)
16 REDFonbet                      0x103782fcc -[LOTRenderGroup updateWithFrame:withModifierBlock:forceLocalUpdate:] (LOTRenderGroup.m:135)
17 REDFonbet                      0x10377df30 -[LOTLayerContainer displayWithFrame:forceUpdate:] (LOTLayerContainer.m:239)
18 REDFonbet                      0x103777300 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
19 REDFonbet                      0x103777300 -[LOTCompositionContainer displayWithFrame:forceUpdate:] (LOTCompositionContainer.m:90)
20 REDFonbet                      0x10377dd18 -[LOTLayerContainer display] (LOTLayerContainer.m:214)
21 QuartzCore                     0x188efeb50 CA::Context::commit_transaction(CA::Transaction*) + 520
22 QuartzCore                     0x188f24eb4 CA::Transaction::commit() + 540
23 QuartzCore                     0x188f25cf4 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
24 CoreFoundation                 0x184f45848 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
25 CoreFoundation                 0x184f43200 __CFRunLoopDoObservers + 412
26 CoreFoundation                 0x184f437bc __CFRunLoopRun + 1292
27 CoreFoundation                 0x184e63fb8 CFRunLoopRunSpecific + 436
28 GraphicsServices               0x186cfbf84 GSEventRunModal + 100
29 UIKit                          0x18e4382f4 UIApplicationMain + 208
30 REDFonbet                      0x10351e2c8 main (main.m:14)
31 libdyld.dylib                  0x18498656c start + 4
```

**Comment by buba447** [comment]
This should be fixed in 2.1.5

**Comment by mrugeshtank** [comment]
I'm still getting is error in 3.1.5.
Installed via Cocoapods.
