### ISSUE TITLE
GitHub API request failed: DoesNotExist

### ISSUE THREAD

**Issue by WuChuming** [airbnb/lottie-ios#66]
I followed the guide to get the Lottie Framework with Carthage, But I get the message indicating "GitHub API request failed: DoesNotExist" on the terminal,I have been searching the solution from network and I am failed. Please tell me how I can solve this problem! Thank you very much！

**Comment by paulsumit1993** [comment]
Try cocoapods

**Comment by buba447** [comment]
@WuChuming just published a dot release which should fix this!

**Comment by WuChuming** [comment]
Thank both of you! I download new files and try "Carthage update" again! The problem is still exist, Terminal shows "GitHub API request failed: DoesNotExist", I have tried Cocoapods at the beginning, Cocoapods is fine, and generates new files as usual, but the program I create can't find the header file of "Lottie.h", I contract the example project and my project, I find out there is missing framework files, I get quit confused at this beginning while the others are using it so well. It seems Carthage will give me those frameworks I need, this is the first time I use it, Sorry for wasting your time. Please tell me what I can do for my next step on using Lottie! Thanks!
