### ISSUE TITLE
Text location from subcomposition seems incorrectly aligned

### ISSUE THREAD

**Issue by joekim** [airbnb/lottie-ios#886]
## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 

The text "TextStyle" should be left aligned.

See lottie-web:
![image](https://user-images.githubusercontent.com/133459/56617570-15d17a00-65d5-11e9-99d1-2abb7bc984f7.png)

## Actual Behavior

The text "TextStyle" appears right aligned.

![image](https://user-images.githubusercontent.com/133459/56617598-2eda2b00-65d5-11e9-8197-ea6c6f2462c5.png)

## Animation JSON

https://drive.google.com/uc?export=download&id=1-QH1Ug7_ZwWcJpLG5_NMK12SfhyFdsoS

See this recently fixed issue in Body Movin' 5.5.2: https://github.com/airbnb/lottie-web/issues/1576

**Comment by sqott** [comment]
I'm noticing this issue arises when text is inside of a text box rather than just a string.

**Comment by imjoeybrennan** [comment]
I'm also having this issue, text in a precomp in a text box. The text box is pushed over about 50% of its width.

**Comment by buba447** [comment]
Just put up a PR that should fix this. https://github.com/airbnb/lottie-ios/pull/1035

Please pull master and verify. Please reopen if not.

**Comment by imjoeybrennan** [comment]
Hey @buba447, thank you for the lightning fast response! I had my engineer (I'm animating it) try again with a pull from master and the issue is still occurring as it did before. Attaching a zip with a demo of the issue in AEP and JSON so you can see the issue on your end.

[lottie-textrendering-issue.zip](https://github.com/airbnb/lottie-ios/files/3663957/lottie-textrendering-issue.zip)

LMK if this helps!

**Comment by seidju** [comment]
Hi @buba447, also having same issue, text is aligned not correctly.

**Comment by buba447** [comment]
Fixed here! https://github.com/airbnb/lottie-ios/pull/1051
